services:
  krabbe-rewrite:
    build:
      context: .
    env_file: .env
    network_mode: host
    develop:
      watch:
        - action: sync+restart
          path: .
          target: /app
    healthcheck:
      test: [ "CMD-SHELL", "ss -ltn | grep ':8090' || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 5